### ISSUE TITLE
Address Information in Stripe UI Card

### ISSUE THREAD

**Issue by Himovic** [AhsanAyaz/flutter_stripe_payments#4]
Hi,

I want add address informations and billing when the user fill the informations about his card. I already tried billingInformation class and prefilledData but it didn't work. How do i proced please ? Thank you

**Comment by AhsanAyaz** [comment]
@Himovic please see my [answer](https://github.com/AhsanAyaz/flutter_stripe_payments/issues/5#issuecomment-647982969)
Feel free to comment or re-open the issue if your problem isn't solved 🙂
