### ISSUE TITLE
Error occur while payment with New or Existing card

### ISSUE THREAD

**Issue by afifPathan** [AhsanAyaz/flutter_stripe_payments#7]
java.lang.NoSuchFieldError: No field type of type Ljava/lang/String; in class Lcom/stripe/android/model/PaymentMethod; or its superclasses (declaration of 'com.stripe.android.model.PaymentMethod' appears in /data/app/com.elsner.woocommerce-4NCBMmjy9J7N3i08OQ-lzA==/base.apk!classes3.dex)

**Comment by AhsanAyaz** [comment]
Have you forked the repo? Did you find why the error would appear?

**Comment by afifPathan** [comment]
Yes, token going to null, Error occur 'payViaExistingCard' method

**Comment by AhsanAyaz** [comment]
Can you create a repo and share so I can have a look?

**Comment by afifPathan** [comment]
Issue solved.


static Future<StripeTransactionResponse> payViaExistingCard(
      {String amount, String currency, CreditCard card}) async {
    try {
      
      /// Add this line.
      var token = await StripePayment.createTokenWithCard(card);

      var paymentMethod = await StripePayment.createPaymentMethod(
          PaymentMethodRequest(card: card, token: token));
      var paymentIntent = await StripeService.createPaymentIntent(
        amount,
        currency,
      );
      var response = await StripePayment.confirmPaymentIntent(PaymentIntent(
          clientSecret: paymentIntent['client_secret'],
          paymentMethodId: paymentMethod.id));
      if (response.status == 'succeeded') {
        return new StripeTransactionResponse(
            message: 'Transaction successful', success: true);
      } else {
        return new StripeTransactionResponse(
            message: 'Transaction failed', success: false);
      }
    } on PlatformException catch (err) {
      print(err);
      return StripeService.getPlatformExceptionErrorResult(err);
    } catch (err) {
      return new StripeTransactionResponse(
          message: 'Transaction failed: ${err.toString()}', success: false);
    }
  }



Thanks for Coordinate

**Comment by AhsanAyaz** [comment]
Thanks @afifPathan .
But I don't think we need to pass both `card` and `token` to create the `PaymentMethod`. We can use either of those.
Anyways, glad it worked out for you 🙂
